name: philip.media Security Policy
description: philip.media Security Policy
url: https://philip-media.github.io/security-policy/
sass:
  style: compressed
version: 1.0.0
remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme
